on:
  push:
    branches:
      - "master"

jobs:
  build-package:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Build dependencies"
        run: "sudo ./install_dependencies.sh"

      - name: "Build toolchain"
        working-directory: "xuantie-gnu-toolchain"
        run: "./configure --prefix=${{ github.workspace }}/output && make linux"

      - name: "Create toolchain archive"
        run: "tar -cJf toolchain.tar.xz output"

      - name: "Upload toolchain artifacts"
        uses: "actions/upload-artifact@v3"
        with:
          name: "toolchain"
          path: "toolchain.tar.xz"

